version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  consul:
    image: "hashicorp/consul:latest"
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0